Fix deploy and further improve release workflow (#77)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,9 +6,17 @@ name: Release
 on:  # yamllint disable-line rule:truthy
   workflow_dispatch:
 
+concurrency:
+  group: alchemy-release
+  cancel-in-progress: true
+
 jobs:
   release:
     runs-on: ubuntu-latest
+
+    env:
+      NEXUS_USER: ${{ secrets.OSS_NEXUS_USERNAME }}
+      NEXUS_PASS: ${{ secrets.OSS_NEXUS_PASSWORD }}
 
     steps:
       - name: Fail if not on valid branch
@@ -39,6 +47,7 @@ jobs:
           echo "$GPG_KEY" | base64 -d > private.key
           gpg --import --batch --yes ./private.key
           rm ./private.key
+          gpg -k
 
       - name: Setup Nexus authentication and GPG passphrase
         uses: whelk-io/maven-settings-xml-action@v21
@@ -51,14 +60,9 @@ jobs:
           }]'
           servers: '[
           {
-            "id": "sonatype-nexus-staging",
-            "username": "${{ secrets.OSS_NEXUS_USERNAME }}",
-            "password": "${{ secrets.OSS_NEXUS_PASSWORD }}"
-          },
-          {
-            "id": "sonatype-nexus-snapshots",
-            "username": "${{ secrets.OSS_NEXUS_USERNAME }}",
-            "password": "${{ secrets.OSS_NEXUS_PASSWORD }}"
+            "id": "ossrh",
+            "username": "${{ env.NEXUS_USER }}",
+            "password": "${{ env.NEXUS_PASS }}"
           }]'
 
       - name: Setup Github SSH key
@@ -74,14 +78,28 @@ jobs:
           echo 'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=' >> ~/.ssh/known_hosts
           echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=' >> ~/.ssh/known_hosts
 
+      - name: Resolve dependencies
+        run: mvn -B dependency:go-offline dependency:resolve-plugins
+
       - name: Prepare release
         id: prepare-release
+        continue-on-error: true
         run: mvn -B release:prepare
 
       - name: Perform release
         id: perform-release
-        run: mvn -B release:perform
+        continue-on-error: true
+        if: ${{ steps.prepare-release.outcome == 'success' }}
+        run: mvn -B release:perform -Darguments='-DskipTests -DskipITs'
 
       - name: Rollback on release failure
         if: ${{ steps.prepare-release.outcome != 'success' || steps.perform-release.outcome != 'success' }}
         run: mvn release:rollback
+
+      # Separate from rollback step so it doesn't look like the rollback itself failed
+      - name: Fail build on release failure
+        if: ${{ steps.prepare-release.outcome != 'success' || steps.perform-release.outcome != 'success' }}
+        run: |
+          echo "Prepare release: ${{ steps.prepare-release.outcome }}"
+          echo "Perform release: ${{ steps.perform-release.outcome }}"
+          exit 1
